development:
  local_item_base_path: 'http://localhost/api/v1/items'
  collections_api_host: '' # setting host to empty disables collection functionality
  collections_api_base_path: '/'
  collections_api_scheme: 'http'
  collections_api_debugging: true
  pid_prefix: 'org.perseids.dev'
  raise_errors: true
test:
  local_item_base_path: 'http://localhost/api/v1/items'
  collections_api_host: '' # setting host to empty disables collection functionality
  collections_api_base_path: '/'
  collections_api_scheme: 'http'
  collections_api_debugging: true
  pid_prefix: 'org.perseids.test'
  raise_errors: false
production:
  local_item_base_path: 'https://sosol.perseids.org/api/v1/items'
  collections_api_host: '' # setting host to empty disables collection functionality
  collections_api_base_path: '/'
  collections_api_scheme: 'http'
  collections_api_debugging: false
  pid_prefix: 'org.perseids'
  raise_errors: false
staging:
  local_item_base_path: 'https://sosol-staging.perseids.org/api/v1/items'
  collections_api_host: '' # setting host to empty disables collection functionality
  collections_api_base_path: '/'
  collections_api_scheme: 'http'
  collections_api_debugging: false
  pid_prefix: 'org.perseids.stage'
  raise_errors: false
