development:
  :cts_api_endpoint : 'http://localhost:8800/exist/rest/db/xq/CTS.xq?'
  :cts_extension_api_endpoint : 'http://localhost:8800/exist/rest/db/xq/CTS-X.xq?'
  :cts_extension_api_put_endpoint : 'http://localhost:8800/exist/rest'
  :cts_inventories : 'perseids-dev|Epi'
  :external_cts_api_endpoints : 'AnnotationSources|http://cts.perseids.org/api/cts/?|http://perseids.org/annotsrc'
  :catalog_search : 'http://catalog.perseus.org/catalog/'
test:
  :cts_api_endpoint : 'http://localhost:8800/exist/rest/db/xq/CTS.xq?'
  :cts_extension_api_endpoint : 'http://localhost:8800/exist/rest/db/xq/CTS-X.xq?'
  :cts_extension_api_put_endpoint : 'http://localhost:8800/exist/rest'
  :cts_inventories : 'perseids-test|Epi'
  :external_cts_api_endpoints : 'AnnotationSources|http://cts.perseids.org/api/cts/?|http://perseids.org/annotsrc'
  :catalog_search : 'http://catalog.perseus.org/catalog/'
production:
  :cts_api_endpoint : 'http://sosol.perseids.org/alpheios/xq/CTS.xq?'
  :cts_extension_api_endpoint : 'http://sosol.perseids.org/alpheios/xq/CTS-X.xq?'
  :cts_extension_api_put_endpoint : 'http://localhost:8800/exist/rest'
  :cts_inventories : 'pilots|Epi,epifacs|Epi,miscellany|Epi,epidoctraining|Epi,visiblewords|Epi,vortex|Epi'
  :external_cts_api_endpoints : 'AnnotationSources|http://cts.perseids.org/api/cts/?|http://perseids.org/annotsrc'
  :catalog_search : 'http://catalog.perseus.org/catalog/'
staging:
  :cts_api_endpoint : 'http://sosol-test.perseids.org/alpheios/xq/CTS.xq?'
  :cts_extension_api_endpoint : 'http://sosol-test.perseids.org/alpheios/xq/CTS-X.xq?'
  :cts_extension_api_put_endpoint : 'http://localhost:8800/exist/rest'
  :cts_inventories : 'pilots|Epi,epifacs|Epi,miscellany|Epi,epidoctraining|Epi,visiblewords|Epi,vortex|Epi'
  :external_cts_api_endpoints : 'AnnotationSources|http://cts.perseids.org/api/cts/?|http://perseids.org/annotsrc'
  :catalog_search : 'http://catalog.perseus.org/catalog/'
