lib/rxsugar:
  :type: git
  :repository: git://github.com/papyri/xsugar.git
  :revision: rails-3-nfd

data/xslt/epidoc:
  :type: subversion
  :repository: https://svn.code.sf.net/p/epidoc/code/trunk/0-example-p5-xslt-LOCKED
  :revision: 1755

data/xslt/perseus/epidoc:
  :type: subversion
  :repository: https://svn.code.sf.net/p/epidoc/code/trunk/0-example-p5-xslt-LOCKED
  :revision: 2380

data/xslt/pn/navigator:
  :type: git
  :repository: git://github.com/papyri/navigator.git
  :revision: c03dd1a2a21ca2cfe72eb0b2cc4306a02db5b4fa

public/javascripts/texAce:
  :type: git
  :repository: git://github.com/perseids-project/texAce.git
  :revision: 7582bdf9950b6eef8fba5b9738a364bdbe9ca884
  :git_enable_submodules: true
  :git_submodules_recursive: true

public/javascripts/imgspect:
  :type: git
  :repository: git://github.com/perseids-project/imgspect.git
  :revision: 0aac5566a5ff85829be4211f91ad3c5d0b53f721
  :git_enable_submodules: true
  :git_submodules_recursive: true

data/xslt/syriaca:
  :type: git
  :repository: git://github.com/srophe/srophe-eXist-app.git
  :revision: 9f66a7e94fd4b58aaaa0bd3a40b1d118e718f49c
